### ISSUE TITLE
Search broken – maybe due to problem with migrations

### ISSUE THREAD

**Issue by svoop** [errbit/errbit#994]
I'm not sure whether this is a general problem or just happening on my install. Since I've updated three days ago, searching for errors results in the following:

> Mongo::Error::OperationFailure: Unable to execute query: error processing query: ns=errbit_production.problems limit=30 skip=0 Tree: $and resolved == false app_id $in [ "5628f08fe252a5601a000002" "563e31cde252a530f3000004" ] TEXT : query=foobar, language=, tag=NULL Sort: { last_notice_at: -1 } Proj: {} planner returned error: need exactly one text index for $text query (17007)

Looking at the migrations, there are three:

    20150527202629_add_v1_to_hipchat_notification_services.rb
    20150926035420_cache_app_on_notice.rb
    201510290041_extract_issue_tracker.rb

However, the following happened during the update:

    rake db:migrate
      Migrating to ExtractIssueTracker (201510290041)
      ==  ExtractIssueTracker: migrating ============================================
      ==  ExtractIssueTracker: migrated (0.0044s) ===================================
      Migrating to AddV1ToHipchatNotificationServices (20150527202629)
      ==  AddV1ToHipchatNotificationServices: migrating =============================
      ==  AddV1ToHipchatNotificationServices: migrated (0.0050s) ====================
      Migrating to CacheAppOnNotice (20150926035420)
      ==  CacheAppOnNotice: migrating ===============================================
      ==  CacheAppOnNotice: migrated (1.2466s) ======================================

    rake db:version
      20150926035420

I'm not familiar with MongoDB so I'm stuck puzzled here.

**Comment by stevecrozz** [comment]
Can you make sure that you both a) are using mongo 2.6+ and b) have run rake db:mongoid:create_indexes

**Comment by svoop** [comment]
That's a yes (mongodb 2.6.8) and another yes (create_indexes done).

**Comment by svoop** [comment]
@stevecrozz 

I've followed [your upgrade instructions[(https://github.com/errbit/errbit#upgrading), however, if I skip the `db:mongoid:remove_undefined_indexes` rake task, the search works fine.

As for the `rake db:version` riddle, I'm somewhat expecting the migrations to be executed ordered by date, maybe I'm wrong there.

**Comment by stevecrozz** [comment]
I can see this problem too now. rake db:mongoid:create_indexes does add the right indices to the mongo database, but rake db:mongoid:remove_undefined_indexes removes the full text index when it should not. It could be a bug in mongoid and I'm going to look into it.

**Comment by stevecrozz** [comment]
Looks like this is indeed a mongoid bug. I've raised the issue on mongodb's issue tracker: https://jira.mongodb.org/browse/MONGOID-4189

I'm going to leave this issue open because this is a problem for errbit too as you've noticed. It could probably be worked around by reversing the instructions to drop the undefined indexes first, then create them. It's not a great workaround because it would drop and recreate a potentially large index, but it would at least keep people from hitting this bug. But let's see if we can get a response from mongodb before we do anything here.

**Comment by estolfo** [comment]
Hi, thanks for reporting that bug in Mongoid, I'm taking a look. I want to confirm that the bug was found on MongoDB server version 2.6.8 ? Thanks

**Comment by stevecrozz** [comment]
@estolfo, @svoop did report the bug using mongodb v2.6.8, but I reproduced it using mongodb v2.6.3, so it seems to affect at least these two versions.

**Comment by estolfo** [comment]
ok cool, I'm looking into it. Thanks!

**Comment by estolfo** [comment]
As of this commit https://github.com/mongodb/mongoid/commit/4bab71a802d42f6156eb8a00b8c53358c23ca5a6 the issue should be fixed in Mongoid master and we be in the 5.0.2 release. Let me know if you have a chance to test it out.

**Comment by IBazylchuk** [comment]
@estolfo i used latest commit from master mongoid, still have same issue. mongo 3.0.2

**Comment by IBazylchuk** [comment]
same if skip db:mongoid:remove_undefined_indexes, then work

**Comment by estolfo** [comment]
Sorry, I'm not sure I understand your last comment. It is working now?

**Comment by svoop** [comment]
Unfortunately, I can't test this right now. My only install at this point is a deployment one which is why I can't easily switch to mongoid from master. However, I hope to get to setup a test clone by the end of the week.

I guess, @IBazylchuk means that if he follows all [steps of the upgrade instructions](https://github.com/errbit/errbit#upgrading), the problem is still there:

    git pull origin master # assuming origin is the github.com/errbit/errbit repo
    bundle install
    rake db:migrate
    rake db:mongoid:create_indexes
    rake db:mongoid:remove_undefined_indexes
    rake assets:precompile

Skipping `rake db:mongoid:remove_undefined_indexes` works around the problem for now without any obvious side-effects.

**Comment by estolfo** [comment]
I've confirmed that this is indeed fixed while testing on MongoDB server version 2.6.11.
Please see my comment on the Jira ticket [here](https://jira.mongodb.org/browse/MONGOID-4189?focusedCommentId=1090273&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1090273).

@IBazylchuk, are you sure you're pointing to mongoid master in your Gemfile? Can you give me more details about your setup that may help me figure out why it's not working for you?

**Comment by tvdeyen** [comment]
I am having the same issue. Upgraded like described above. Then tried to revert like @stevecrozz said in https://github.com/errbit/errbit/issues/994#issuecomment-156190291

* `rake db:mongoid:remove_undefined_indexes`
* `rake db:mongoid:create_indexes`

Removing indexes worked.

Re-creating the indexes failed with:

```
Notice: no rspec tasks available in this environment
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
MONGOID: Created indexes on Backtrace:
MONGOID: Index: {:fingerprint=>1}, Options: {}
MONGOID: Created indexes on Comment:
MONGOID: Index: {:user_id=>1}, Options: {}
MONGOID: Index ignored on: Deploy, please define in the root model.
MONGOID: Created indexes on Err:
MONGOID: Index: {:problem_id=>1}, Options: {}
MONGOID: Index: {:fingerprint=>1}, Options: {}
MONGOID: Created indexes on Notice:
MONGOID: Index: {:backtrace_id=>1}, Options: {:background=>true}
MONGOID: Index: {:created_at=>1}, Options: {}
MONGOID: Index: {:err_id=>1, :created_at=>1, :_id=>1}, Options: {}
rake aborted!
Mongo::Error::OperationFailure: exception: Found pre-existing index { v: 1, key: { error_class: "text", where: "text", message: "text", app_name: "text", environment: "text" }, ns: "errbit.problems", default_language: "english", name: "error_class_text_where_text_message_text_app_name_text_environment_text" } with invalid type 'text'. Disallowing creation of new index type 'text'. See http://dochub.mongodb.org/core/index-type-changes (67)
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/result.rb:226:in `validate!'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/write/write_command_enabled.rb:48:in `execute_write_command'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/write/write_command_enabled.rb:38:in `execute'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/index/view.rb:150:in `create_many'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/index/view.rb:125:in `create_one'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:37:in `block in create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:31:in `each'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:31:in `create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:20:in `block in create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:17:in `each'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:17:in `create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rake:8:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)
```

I am on Mongodb v3.0.7

Then tried to use `mongoid` master even then removing the index fails.

**Comment by stevecrozz** [comment]
Playing around with the latest mongoid seems to cure the problem for me:
https://github.com/stevecrozz/errbit/tree/mongoid51

I can see that the indices are created when I run rake db:mongoid:create_indexes, and they are not removed when I run rake db:mongoid:remove_undefined_indexes. If I add extra indices, they are removed as expected. I'll put in a PR for this when the new mongo version is released.
```bash
~/Projects/errbit/errbit (mongoid51)$ rake db:mongoid:create_indexes
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
MONGOID: Created indexes on Backtrace:
MONGOID: Index: {:fingerprint=>1}, Options: {}
MONGOID: Created indexes on Comment:
MONGOID: Index: {:user_id=>1}, Options: {}
MONGOID: Created indexes on Err:
MONGOID: Index: {:problem_id=>1}, Options: {}
MONGOID: Index: {:fingerprint=>1}, Options: {}
MONGOID: Created indexes on Notice:
MONGOID: Index: {:backtrace_id=>1}, Options: {:background=>true}
MONGOID: Index: {:created_at=>1}, Options: {}
MONGOID: Index: {:err_id=>1, :created_at=>1, :_id=>1}, Options: {}
MONGOID: Created indexes on Problem:
MONGOID: Index: {:app_id=>1}, Options: {}
MONGOID: Index: {:app_name=>1}, Options: {}
MONGOID: Index: {:message=>1}, Options: {}
MONGOID: Index: {:last_notice_at=>1}, Options: {}
MONGOID: Index: {:first_notice_at=>1}, Options: {}
MONGOID: Index: {:resolved_at=>1}, Options: {}
MONGOID: Index: {:notices_count=>1}, Options: {}
MONGOID: Index: {:error_class=>"text", :where=>"text", :message=>"text", :app_name=>"text", :environment=>"text"}, Options: {:default_language=>"english"}
MONGOID: Created indexes on User:
MONGOID: Index: {:authentication_token=>1}, Options: {}
~/Projects/errbit/errbit (mongoid51)$ rake db:mongoid:remove_undefined_indexes
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
```

**Comment by stevecrozz** [comment]
@tvdeyen I'm not sure what's happening in your scenario. Maybe you can get past it by removing that index from the mongo console: https://docs.mongodb.org/manual/reference/method/db.collection.dropIndex/#db.collection.dropIndex

**Comment by tvdeyen** [comment]
@stevecrozz thanks! I could manage to drop the old index with `db.problems.dropIndex()`, but now I get following error:

```
rake aborted!
Mongo::Error::OperationFailure: exception: Btree::insert: key too large to index, failing errbit.problems.$message_1 6425 { : "MultiJson::ParseError: 795: unexpected token at '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-stri..." } (17280)
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/result.rb:226:in `validate!'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/write/write_command_enabled.rb:48:in `execute_write_command'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/operation/write/write_command_enabled.rb:38:in `execute'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/index/view.rb:150:in `create_many'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/index/view.rb:125:in `create_one'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:37:in `block in create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:31:in `each'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/indexable.rb:31:in `create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:20:in `block in create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:17:in `each'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rb:17:in `create_indexes'
/var/www/errbit/vendor/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/tasks/database.rake:8:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)
```

I guess this is related to https://github.com/errbit/errbit/issues/848

I'm on latest mongoid, errbit and mongodb.

Thanks for your help.

**Comment by stevecrozz** [comment]
Oh no! This means you already have data in your DB that cannot be indexed. Since you didn't have the index to begin with, the error described in #848 never prevented you from inserting the error that cannot be indexed. The path forward is to either delete the problems that have messages that are too long, or to truncate those messages.

I think first we need to fix #1001, and then we can whip up a console task to fix up your app.

**Comment by stevecrozz** [comment]
@svoop #1001 is fixed. do you want some help fixing up your long messages so you can get the text index installed?

**Comment by svoop** [comment]
@stevecrozz Cool, yes, I'm not (yet) very fluent with Mongo, so I appreciate your help very much.

**Comment by stevecrozz** [comment]
@svoop If you can handle losing your notices with long messages you could drop them like this from your mongo console:
```
> db.notices.remove({ $where: 'this.message.length > 1000' })
WriteResult({ "nRemoved" : 2 })
> db.problems.remove({ $where: 'this.message.length > 1000' })
WriteResult({ "nRemoved" : 2 })
```

If you want to see how much you'll lose you could count your long notices like this:
```
> db.notices.find({ $where: 'this.message.length > 1000' }).count()
9
> db.problems.find({ $where: 'this.message.length > 1000' }).count()
3
```

**Comment by tvdeyen** [comment]
@stevecrozz nice and how can I truncate them instead of deleting them?

**Comment by tvdeyen** [comment]
@stevecrozz also I get this error:

```
> db.problems.find({ $where: 'this.message.length > 1000' }).count()
2015-12-18T12:07:35.239+0100 E QUERY    Error: count failed: {
	"errmsg" : "exception: TypeError: Cannot read property 'length' of undefined\n    at _funcs1 (_funcs1:1:42) near '1000' ",
	"code" : 16722,
	"ok" : 0
}
    at Error (<anonymous>)
    at DBQuery.count (src/mongo/shell/query.js:326:11)
    at (shell):1:60 at src/mongo/shell/query.js:326
```

I guess `message` does not exist as column on `problems`?

**Comment by tvdeyen** [comment]
@stevecrozz updated the second query to:

```
db.problems.find({ $where: 'this.message && this.message.length > 1000' }).count()
```

**Comment by svoop** [comment]
@stevecrozz 

I've removed to oversize messages, both counts return 0 now. then I've repeated the steps from the install/update guide without any errors:

    bundle exec rake db:migrate RAILS_ENV=production
    bundle exec rake db:mongoid:create_indexes RAILS_ENV=production
    bundle exec rake db:mongoid:remove_undefined_indexes RAILS_ENV=production

However, the search still doesn't work:

> Mongo::Error::OperationFailure: Unable to execute query: error processing query: ns=errbit_production.problems limit=30 skip=0 Tree: $and app_id $in [ "5628f08fe252a5601a000002" ] TEXT : query=state, language=, tag=NULL Sort: { last_notice_at: -1 } Proj: {} planner returned error: need exactly one text index for $text query (17007)

Tried on the current HEAD of Master. Any idea what I'm doing wrong here?

**Comment by stevecrozz** [comment]
@svoop Can you hop on https://gitter.im/errbit/errbit so we can chat in real-time? I'm sure we can figure this out.

**Comment by stevecrozz** [comment]
I believe @svoop was hitting the same mongoid bug as described earlier and a new version of mongoid has not yet been published that includes the fix. So I'm changing the docs to reverse the instructions for creating/removing indexes which should result in the correct state even when mongoid is misbehaving. This change should prevent #994 from returning.

**Comment by estolfo** [comment]
Hi, mongoid 5.0.2 is released and contains the fix for this.

**Comment by tvdeyen** [comment]
Just for later reference:

I managed to truncate the long messages in the rails console. Then run all rake tasks again and it worked. After updating to mongoid 0.5.2 the search works again! Finally :)

So, please merge #1030 soon, it works!

Thanks for all the help

**Comment by estolfo** [comment]
awesome!
Just as a note - it was Mongoid 5.0.2 =)

**Comment by tvdeyen** [comment]
Sorry, updated the comment

**Comment by estolfo** [comment]
no problem!

**Comment by stevecrozz** [comment]
Solved by #1030. Thanks everyone.
